resources:
- deployment.yaml
- <APPLICATIONNAME>-global-devices-config.yaml
- <APPLICATIONNAME>-global-devices-secret.yaml
- <APPLICATIONNAME>-pvc-device-data.yml
- <APPLICATIONNAME>-app-config.yaml

